SET search_path TO bakery_db;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS preferences JSONB DEFAULT '{}'::jsonb;
ALTER TABLE baking_goods ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS allergens TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE bakeries ADD COLUMN IF NOT EXISTS working_hours TSRANGE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS price_range NUMRANGE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS search_tsv TSVECTOR;

